### ISSUE TITLE
move the arc examples here

### ISSUE THREAD

**Issue by timm** [yrahul3910/raise#25]
move the arc examples here (to /examples)

**Comment by yrahul3910** [comment]
This feels out-of-scope for this project. Perhaps we should instead set up a new repo with onboarding material for newbies? Happy to set that up with you.

**Comment by timm** [comment]
On Thu, May 23, 2024 at 7:44 PM Rahul Yedida ***@***.***>
wrote:

> This feels out-of-scope for this project. Perhaps we should instead set up
> a new repo with onboarding material for newbies? Happy to set that up with
> you.
>

Just do it ! U and Amir Ali

T
